### ISSUE TITLE
Make server launch with no USB devices connected

### ISSUE THREAD

**Issue by HarryMadden** [kilejna/rc-fpv#6]
Server/GUI will not launch if there is no Arduino connected or if it doesn't recognise a boardPort

Recommend that GUI launches but displays a message advising no USB device detected (or a dropdown to select a boardPort?)

```bash
npm run start:server
```
Returns:
``` bash
1707633642050 Error Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02  
node:events:508
    const err = new ERR_UNHANDLED_ERROR(stringifiedEr);
                ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  type: 'error',
  timestamp: 1707633642050,
  class: 'Error',
  message: 'Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02',
  data: null
})
    at Board.emit (node:events:508:17)
    at Board.log (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:637:8)
    at Board.<computed> [as error] (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:648:14)
    at Board.finalizeAndBroadcast (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:363:12)
    at /Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:147:18
    at SerialPort.<anonymous> (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/firmata-io/lib/firmata.js:613:9)
    at SerialPort.emit (node:events:519:28)
    at SerialPort.emit (node:domain:488:12)
    at SerialPort._error (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/@serialport/stream/lib/index.js:200:10)
    at /Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/@serialport/stream/lib/index.js:242:12 {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    type: 'error',
    timestamp: 1707633642050,
    class: 'Error',
    message: 'Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02',
    data: null
  }
}
```

**Comment by HarryMadden** [comment]
We may be able to avoid having to input boardPort into server.ts before building it if we can implement a dropdown that includes all USB devices using WebUSB API:
- [https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API]()

**Comment by kilejna** [comment]
> We may be able to avoid having to input boardPort into server.ts before building it if we can implement a dropdown that includes all USB devices using WebUSB API:
> 
>     * https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API

Currently the [WebUSB API](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API) is in experimental phase and features that would be required to listen for [USBConnectionEvents](https://developer.mozilla.org/en-US/docs/Web/API/USBConnectionEvent#browser_compatibility) lacks support for common browsers such as Firefox and Safari. In saying that, from the looks of it, this API might _potentially_ reduce the need for johnny-five. I'm happy to create a separate branch to play with it - but again it would be experimental only c:

**Comment by kilejna** [comment]
> Server/GUI will not launch if there is no Arduino connected or if it doesn't recognise a boardPort
> 
> Recommend that GUI launches but displays a message advising no USB device detected (or a dropdown to select a boardPort?)
> 
> ```shell
> npm run start:server
> ```
> 
> Returns:
> 
> ```shell
> 1707633642050 Error Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02  
> node:events:508
>     const err = new ERR_UNHANDLED_ERROR(stringifiedEr);
>                 ^
> 
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
>   type: 'error',
>   timestamp: 1707633642050,
>   class: 'Error',
>   message: 'Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02',
>   data: null
> })
>     at Board.emit (node:events:508:17)
>     at Board.log (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:637:8)
>     at Board.<computed> [as error] (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:648:14)
>     at Board.finalizeAndBroadcast (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:363:12)
>     at /Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/johnny-five/lib/board.js:147:18
>     at SerialPort.<anonymous> (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/firmata-io/lib/firmata.js:613:9)
>     at SerialPort.emit (node:events:519:28)
>     at SerialPort.emit (node:domain:488:12)
>     at SerialPort._error (/Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/@serialport/stream/lib/index.js:200:10)
>     at /Users/osx/Desktop/FPV-RC/rc-fpv/server/node_modules/@serialport/stream/lib/index.js:242:12 {
>   code: 'ERR_UNHANDLED_ERROR',
>   context: {
>     type: 'error',
>     timestamp: 1707633642050,
>     class: 'Error',
>     message: 'Error: No such file or directory, cannot open /dev/tty.usbmodemDC5475CBEFC02',
>     data: null
>   }
> }
> ```

I'm not sure if it is possible to get a drop down list of usb devices that are not audio and video. I can try to find a work around and also try to implement a way to manually enter the config in the web gui instead of having to rebuild the server.
